language: node_js
node_js:
- 12
script:
- npm test
- npm run build
- eval "$(ssh-agent -s)"
- ssh-keyscan -H 95.163.212.32 >> ~/.ssh/known_hosts
- chmod 400 $HOME/.ssh/deploy-2019-2-mGznqKVh.pem
- scp -i $HOME/.ssh/deploy-2019-2-mGznqKVh.pem -r ./build/* ubuntu@95.163.212.32:/home/ubuntu/beepteam.ru
before_install:
- openssl aes-256-cbc -K $encrypted_70f3d4d2943f_key -iv $encrypted_70f3d4d2943f_iv
  -in deploy-2019-2-mGznqKVh.pem.enc -out ~\/Downloads/deploy-2019-2-mGznqKVh.pem
  -d
- openssl aes-256-cbc -K $encrypted_70f3d4d2943f_key -iv $encrypted_70f3d4d2943f_iv
  -in deploy-2019-2-mGznqKVh.pem.enc -out $HOME/.ssh/deploy-2019-2-mGznqKVh.pem -d
